# NOTE: this toml config is a preset for 8 H100 GPUs (with 96GiB memory).

[job]
dump_folder = "./outputs"
description = "Qwen3 32B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 10

[metrics]
log_freq = 10
enable_tensorboard = false
save_tb_folder = "tb"

[model]
name = "qwen3"
flavor = "32B"
hf_assets_path = "./assets/hf/Qwen3-32B"
# converters = ["float8"]

[optimizer]
name = "AdamW"
lr = 8e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 11  # lr scheduler warm up, 20% total steps

[training]
local_batch_size = 2
seq_len = 2048
max_norm = 1.0  # grad norm clipping
steps = 11
dataset = "c4"

[comm]
backend = "gloo"     # Literal['nccl', 'gloo', 'auto']

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = 16
fsdp_reshard_after_forward = "default" # default / never / always
tensor_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable = false
folder = "checkpoint"
interval = 500
last_save_model_only = false
export_dtype = "float16"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = "full"  # ["none", "selective", "full"]
selective_ac_option = "op"  # "int" = ac every positive int layer or 'op', ac based on ops policy

[compile]
enable=false
components = ["model", "loss"]

[quantize.linear.float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output"]
